// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwevnbKppMy0jk5Odaw_4kjEcKUHX84-U',
    appId: '1:520417668823:web:6c843700da76410b964a92',
    messagingSenderId: '520417668823',
    projectId: 'first-app-980a7',
    authDomain: 'first-app-980a7.firebaseapp.com',
    databaseURL: 'https://first-app-980a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-980a7.appspot.com',
    measurementId: 'G-4N99DMSX9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46y3KW7QrgR1pCElHFiy70-rGQxY3svs',
    appId: '1:520417668823:android:afeb794468fec949964a92',
    messagingSenderId: '520417668823',
    projectId: 'first-app-980a7',
    databaseURL: 'https://first-app-980a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-980a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8lf7HoUGsN087P89LqY1x-GRbdvmkSVg',
    appId: '1:520417668823:ios:561a96c7417f3533964a92',
    messagingSenderId: '520417668823',
    projectId: 'first-app-980a7',
    databaseURL: 'https://first-app-980a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-980a7.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8lf7HoUGsN087P89LqY1x-GRbdvmkSVg',
    appId: '1:520417668823:ios:00db60ec587375c5964a92',
    messagingSenderId: '520417668823',
    projectId: 'first-app-980a7',
    databaseURL: 'https://first-app-980a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-980a7.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
